name: Automatic Deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
<<<<<<< HEAD
        run: echo Start deploying
=======
        run: echo Start deploying SenHub
      - name: Deploy static to Render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
>>>>>>> 26b57e4988c91950631ecb1b10e17ce870494172
      - name: Checkout git
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Deploy core to gh-pages branch
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
<<<<<<< HEAD
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 26b57e4988c91950631ecb1b10e17ce870494172
